// TUNES------------------------------------------------------
export const FETCH_TUNES = 'FETCH_TUNES'
export const FETCH_TUNES_START = 'FETCH_TUNES_START'
export const FETCH_TUNES_SUCCESS = 'FETCH_TUNES_SUCCESS'
export const FETCH_TUNES_FAIL = 'FETCH_TUNES_FAIL'

export const CREATE_TUNE = 'CREATE_TUNE'
export const CREATE_TUNE_START = 'CREATE_TUNE_START'
export const CREATE_TUNE_SUCCESS = 'CREATE_TUNE_SUCCESS'
export const CREATE_TUNE_FAIL = 'CREATE_TUNE_FAIL'

export const DELETE_TUNE = 'DELETE_TUNE'
export const DELETE_TUNE_START = 'DELETE_TUNE_START'
export const DELETE_TUNE_SUCCESS = 'DELETE_TUNE_SUCCESS'
export const DELETE_TUNE_FAIL = 'DELETE_TUNE_FAIL'

export const UPDATE_TUNE = 'UPDATE_TUNE'
export const UPDATE_TUNE_START = 'UPDATE_TUNE_START'
export const UPDATE_TUNE_SUCCESS = 'UPDATE_TUNE_SUCCESS'
export const UPDATE_TUNE_FAIL = 'UPDATE_TUNE_FAIL'


// TEACHERS------------------------------------------------------
export const FETCH_TEACHERS = 'FETCH_TEACHERS'
export const FETCH_TEACHERS_START = 'FETCH_TEACHERS_START'
export const FETCH_TEACHERS_SUCCESS = 'FETCH_TEACHERS_SUCCESS'
export const FETCH_TEACHERS_FAIL = 'FETCH_TEACHERS_FAIL'

export const CREATE_TEACHER = 'CREATE_TEACHER'
export const CREATE_TEACHER_START = 'CREATE_TEACHER_START'
export const CREATE_TEACHER_SUCCESS = 'CREATE_TEACHER_SUCCESS'
export const CREATE_TEACHER_FAIL = 'CREATE_TEACHER_FAIL'

export const DELETE_TEACHER = 'DELETE_TEACHER'
export const DELETE_TEACHER_START = 'DELETE_TEACHER_START'
export const DELETE_TEACHER_SUCCESS = 'DELETE_TEACHER_SUCCESS'
export const DELETE_TEACHER_FAIL = 'DELETE_TEACHER_FAIL'

export const UPDATE_TEACHER = 'UPDATE_TEACHER'
export const UPDATE_TEACHER_START = 'UPDATE_TEACHER_START'
export const UPDATE_TEACHER_SUCCESS = 'UPDATE_TEACHER_SUCCESS'
export const UPDATE_TEACHER_FAIL = 'UPDATE_TEACHER_FAIL'


// RESOURCES------------------------------------------------------
export const FETCH_RESOURCES = 'FETCH_RESOURCES'
export const FETCH_RESOURCES_START = 'FETCH_RESOURCES_START'
export const FETCH_RESOURCES_SUCCESS = 'FETCH_RESOURCES_SUCCESS'
export const FETCH_RESOURCES_FAIL = 'FETCH_RESOURCES_FAIL'

export const CREATE_RESOURCE = 'CREATE_RESOURCE'
export const CREATE_RESOURCE_START = 'CREATE_RESOURCE_START'
export const CREATE_RESOURCE_SUCCESS = 'CREATE_RESOURCE_SUCCESS'
export const CREATE_RESOURCE_FAIL = 'CREATE_RESOURCE_FAIL'

export const DELETE_RESOURCE = 'DELETE_RESOURCE'
export const DELETE_RESOURCE_START = 'DELETE_RESOURCE_START'
export const DELETE_RESOURCE_SUCCESS = 'DELETE_RESOURCE_SUCCESS'
export const DELETE_RESOURCE_FAIL = 'DELETE_RESOURCE_FAIL'

export const UPDATE_RESOURCE = 'UPDATE_RESOURCE'
export const UPDATE_RESOURCE_START = 'UPDATE_RESOURCE_START'
export const UPDATE_RESOURCE_SUCCESS = 'UPDATE_RESOURCE_SUCCESS'
export const UPDATE_RESOURCE_FAIL = 'UPDATE_RESOURCE_FAIL'


// LESSONS------------------------------------------------------
export const FETCH_LESSONS = 'FETCH_LESSONS'
export const FETCH_LESSONS_START = 'FETCH_LESSONS_START'
export const FETCH_LESSONS_SUCCESS = 'FETCH_LESSONS_SUCCESS'
export const FETCH_LESSONS_FAIL = 'FETCH_LESSONS_FAIL'

export const CREATE_LESSON = 'CREATE_LESSON'
export const CREATE_LESSON_START = 'CREATE_LESSON_START'
export const CREATE_LESSON_SUCCESS = 'CREATE_LESSON_SUCCESS'
export const CREATE_LESSON_FAIL = 'CREATE_LESSON_FAIL'

export const DELETE_LESSON = 'DELETE_LESSON'
export const DELETE_LESSON_START = 'DELETE_LESSON_START'
export const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS'
export const DELETE_LESSON_FAIL = 'DELETE_LESSON_FAIL'

export const UPDATE_LESSON = 'UPDATE_LESSON'
export const UPDATE_LESSON_START = 'UPDATE_LESSON_START'
export const UPDATE_LESSON_SUCCESS = 'UPDATE_LESSON_SUCCESS'
export const UPDATE_LESSON_FAIL = 'UPDATE_LESSON_FAIL'

// LESSON_RESOURCES------------------------------------------------------
export const FETCH_LESSON_RESOURCES = 'FETCH_LESSON_RESOURCES'
export const FETCH_LESSON_RESOURCES_START = 'FETCH_LESSON_RESOURCES_START'
export const FETCH_LESSON_RESOURCES_SUCCESS = 'FETCH_LESSON_RESOURCES_SUCCESS'
export const FETCH_LESSON_RESOURCES_FAIL = 'FETCH_LESSON_RESOURCES_FAIL'

export const CREATE_LESSON_RESOURCE = 'CREATE_LESSON_RESOURCE'
export const CREATE_LESSON_RESOURCE_START = 'CREATE_LESSON_RESOURCE_START'
export const CREATE_LESSON_RESOURCE_SUCCESS = 'CREATE_LESSON_RESOURCE_SUCCESS'
export const CREATE_LESSON_RESOURCE_FAIL = 'CREATE_LESSON_RESOURCE_FAIL'

export const DELETE_LESSON_RESOURCE = 'DELETE_LESSON_RESOURCE'
export const DELETE_LESSON_RESOURCE_START = 'DELETE_LESSON_RESOURCE_START'
export const DELETE_LESSON_RESOURCE_SUCCESS = 'DELETE_LESSON_RESOURCE_SUCCESS'
export const DELETE_LESSON_RESOURCE_FAIL = 'DELETE_LESSON_RESOURCE_FAIL'

export const UPDATE_LESSON_RESOURCE = 'UPDATE_LESSON_RESOURCE'
export const UPDATE_LESSON_RESOURCE_START = 'UPDATE_LESSON_RESOURCE_START'
export const UPDATE_LESSON_RESOURCE_SUCCESS = 'UPDATE_LESSON_RESOURCE_SUCCESS'
export const UPDATE_LESSON_RESOURCE_FAIL = 'UPDATE_LESSON_RESOURCE_FAIL'
